language: node_js
node_js:
  - 10
script:
  # Test the components
  - npm run test
  # Transpile the components to js
  - npm run build
  # Code coverage
  - npm install codecov -g
after_success:
  - codecov
